### ISSUE TITLE
Catch AWS SDK error events.

### ISSUE THREAD

**Issue by kixxauth** [kixxauth/kixx-rynodb#1]
When there is a network error, we get unfriendly results like this:

```
Error: connect ECONNREFUSED 127.0.0.1:4567
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

**Comment by kixxauth** [comment]
A better example of the full stack:

```
Exiting with error(s):
-- Reporting error 1 of 4:
StackedError: Error in getObject() store middleware: Error in RynoDB get(): Error in dynamodb get(): connect ECONNREFUSED 127.0.0.1:4567
-- End of error 1 of 4 --

-- Reporting error 2 of 4:
StackedError: Error in RynoDB get(): Error in dynamodb get(): connect ECONNREFUSED 127.0.0.1:4567
-- End of error 2 of 4 --

-- Reporting error 3 of 4:
StackedError: Error in dynamodb get(): connect ECONNREFUSED 127.0.0.1:4567
-- End of error 3 of 4 --

-- Reporting error 4 of 4:
Error: connect ECONNREFUSED 127.0.0.1:4567
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
-- End of error 4 of 4 --
```

**Comment by kixxauth** [comment]
Additionally, strip off the statusCode since it triggers actual Express.js HTTP error handling middleware:

```
{ ResourceNotFoundException: Requested resource not found
    at Request.extractError (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/kris/Projects/odd-core/node_modules/aws-sdk/lib/event_listeners.js:269:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  message: 'Requested resource not found',
  code: 'ResourceNotFoundException',
  time: 2017-12-11T15:32:49.019Z,
  requestId: 'Y0FGCOYTJQ9RESFVM1XJC9HRZ0O0J18FBMBHSFZSDBTKZOBTES0W',
  statusCode: 400,
  retryable: false,
  retryDelay: 12.907883677051736 }
```

**Comment by kixxauth** [comment]
Fixed: No longer using AWS SDK
